services:

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: pessoaapi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - pessoa
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: pessoaapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pessoa

networks:
  pessoa:
    driver: bridge
